
development:
  adapter: postgresql
  encoding: unicode
  database: glintDBv1
  pool: 5
  username: jay1
  password: jay1

test:
  adapter: postgresql
  encoding: unicode
  database: glintDBv1
  pool: 5
  username: jay1
  password: jay1

production:
  adapter: postgresql
  encoding: unicode
  database: glintDBv1
  pool: 5
  username: jay1
  password: jay1